services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: igaming-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=igaming
      - PORT=8080
    volumes:
      - ./docs:/app/docs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - igaming-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    container_name: igaming-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: igaming
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - igaming-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "-p$password",
        ]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  igaming-network:
    driver: bridge

volumes:
  db_data:
